dist: xenial
language: python
cache: pip
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
env:
  - DJANGO=3.2
  - DJANGO=4.0
jobs:
  fast_finish: true
install: pip install tox-travis codecov
script: tox
after_success:
  - codecov